name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes (adjust as you like)
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update activity section
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "✨ updated activity in README"
          MAX_LINES: 10
          TARGET_FILE: README.md
